[package]
name = "rust-renderer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "HtmlCanvasElement",
    "WebGl2RenderingContext",
    "WebGlBuffer",
    "WebGlProgram",
    "WebGlShader",
    "WebGlUniformLocation", 
    "WebGlVertexArrayObject",
    "MouseEvent",
    "console",
    ] }
js-sys = "0.3"
cgmath = "0.18.0"
getrandom = { version = "0.3.2", features = ["wasm_js"] }
rand = "0.9.1"
wavefront_rs = { git = "https://github.com/replicadse/wavefront_rs.git" }
